---
# file: tasks/install_haproxy.yml 
- name: Install HA Proxy (DEB)
  apt: 
    pkg: haproxy 
    state: present
  when: ansible_os_family == 'Debian'

- name: Install HA Proxy (YUM)
  yum: 
    name: haproxy 
    state: present
  when: ansible_os_family == 'RedHat'